### ISSUE TITLE
Error in Running generate_data function in the example provided in the documentation.

### ISSUE THREAD

**Issue by Tanmay-Kulkarni101** [inovex/justcause#25]
I was running the subsection on [Parametric DGPs](https://justcause.readthedocs.io/en/latest/usage.html#parametric-dgps) for the following code snippet: 
```
from justcause.data.utils import generate_data

replications = generate_data(
    covariates,
    treatment,
    outcome,
    n_samples=747,  # Optional but 747 is the maximum available with IHDP covariates
    n_replications=100,
    random_state=42  # Fix random_state for replicability
)
```

when I encountered the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-65-035bbd098881> in <module>
      7     n_samples=747,  # Optional but 747 is the maximum available with IHDP covariates
      8     n_replications=100,
----> 9     random_state=42,  # Fix random_state for replicability
     10 )

~/model_env/lib/python3.7/site-packages/justcause/data/utils.py in generate_data(covariates, treatment, outcomes, n_samples, n_replications, covariate_names, random_state, **kwargs)
    162     else:
    163         indices = random_state.choice(covariates.shape[0], n_samples, replace=False)
--> 164         covariates = covariates[indices, :]
    165 
    166     if covariate_names is None:

~/model_env/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2798             if self.columns.nlevels > 1:
   2799                 return self._getitem_multilevel(key)
-> 2800             indexer = self.columns.get_loc(key)
   2801             if is_integer(indexer):
   2802                 indexer = [indexer]

~/model_env/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2644                 )
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:
   2648                 return self._engine.get_loc(self._maybe_cast_indexer(key))

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

TypeError: '(array([208, 259,  97, 148, 395, 487, 234, 181, 526, 367, 260, 368, 523,
       396, 351,  77, 609, 420, 174, 743,  39, 620, 375, 665, 650, 296,
       192, 538, 626, 231, 299, 416, 346, 480,  76,  81, 549, 314, 323,
       425,  33, 450, 554,  78, 464,  66, 388, 319,  10, 725, 482, 338,
       399, 101, 247, 223, 118,  54, 158, 586, 713, 239, 211, 715, 451,
        65, 426, 281, 422, 490, 697, 745, 215, 336, 623,  72, 210, 658,
       417,  63, 638, 361,  49, 349, 155, 733, 604, 332, 473,  23, 264,
       742, 601, 165, 218, 703, 109,  86, 275,   2, 579, 133,  30, 619,
       693, 440, 300, 120, 724, 572, 380, 611, 294, 536, 430, 356,  84,
       706,  79, 235, 530, 248, 363,  31, 362, 529, 580, 433, 198,  55,
       695, 596, 516, 431, 212, 324,  60, 704, 448, 446, 679, 485, 412,
        90, 685, 598,  69, 453, 131,  44,  70, 164, 682, 265, 250, 135,
       617,  28, 594, 381, 707, 136, 204,   6, 334,  73, 244, 196, 145,
       615, 669, 132, 434, 377, 698,  41, 108, 292,  56, 220, 290, 350,
       618, 506,  24, 199, 213, 394, 327, 445, 110,  82,  51, 531, 599,
       653, 569, 405, 342, 139, 449, 227,  18, 544, 140, 302, 499,  83,
        61, 551, 439,  29, 331, 328, 371, 398, 182, 507, 344, 429, 468,
       494, 645, 355, 209, 382, 423, 176, 500, 640, 311, 628, 266, 137,
       664, 709, 728, 163, 333, 656, 684, 674, 404, 408, 527, 714, 104,
       114, 671, 254, 670, 585,  92,   7,  89, 567, 588, 467, 692, 595,
       424,  11,  43,  42, 167, 654, 352, 178, 470, 535, 177, 514, 521,
       257, 306,  15, 443, 256, 326, 335, 286, 411, 357, 291, 393,   9,
       249,  22, 221, 501, 481, 731, 710, 624, 203, 542,  93, 652, 727,
       457, 284, 184, 603, 340, 153,  75, 677, 277,  68, 616, 188, 271,
       236,  88, 633, 117, 125, 613, 289, 238,   0, 738, 329, 651, 741,
       278, 582, 116, 228, 360, 465, 274, 318, 512, 144, 486, 436, 675,
       545, 268, 528, 307, 310,  46, 261, 195, 746, 625, 107,  59, 559,
       641, 100, 583, 668, 543, 390, 179, 304, 369, 409, 718, 149, 124,
       591, 648, 185, 575, 734, 608, 736, 477, 321, 353, 688, 142, 737,
       141, 456, 320,  19, 172, 607, 312, 694,  12, 305, 354,  25, 557,
       169,  38, 469, 245, 298, 621, 503, 272, 570, 154, 126, 532, 341,
       287, 113, 428, 173, 359, 643,  57, 513, 222, 280,  17, 578, 322,
       255, 627, 558, 716, 190, 571, 660, 432,  94, 180, 301, 495, 550,
       522, 519, 659, 497,   5, 732,  45, 462, 690, 171,  16,  48, 722,
       683,   3, 537, 478, 316, 447, 687, 283,  96, 285, 479, 225,  26,
       587, 263, 437,  50, 364, 229,  37, 157, 237, 717, 374, 370, 442,
       719, 175, 634, 127, 552, 194, 636, 644, 493, 515, 525, 721, 622,
       642,  67, 511, 483, 168, 444, 517, 162, 309, 193, 534, 365, 383,
       673, 541, 152, 518, 533, 111, 226, 606, 597, 103, 421, 419, 584,
       705,  74, 115, 407, 720, 119,  53, 151, 403, 702, 207, 629, 602,
         8, 605,  36, 452, 253, 303, 676, 539, 547, 262, 297, 414, 150,
       593, 730, 488, 147, 146, 548, 691, 680, 348, 463, 325, 186, 123,
       635, 143, 712, 197, 279, 293, 400, 122, 183, 202, 438, 246, 415,
       662, 129, 402, 589, 581, 219, 678, 568, 711, 576, 386, 723, 509,
       267, 739, 441, 496, 112, 232, 649, 373, 233, 590, 317, 410, 667,
       358, 258, 282, 376, 384, 224, 708, 610, 472, 347, 505, 735, 689,
       672, 637, 630, 556, 577,  85, 242, 159, 524,  35, 540, 170, 639,
       631, 701,  95, 563, 240, 574, 460, 553, 655, 206, 392, 397, 632,
       217,   4, 666, 612, 546,  98, 573, 406, 502,  47,  32, 200, 134,
        27, 657, 230, 489, 378, 288, 418, 391, 592, 498, 138,  62, 471,
       647, 128, 726, 520,  64,  14, 156,  40, 492, 379, 187, 216,  52,
       337, 295, 251, 461, 455, 744, 269, 201, 161, 555, 401, 476, 105,
       565, 389,   1, 696, 561,  80, 205,  34, 508, 427, 454, 366,  91,
       339, 564, 345, 241,  13, 315, 600, 387, 273, 166, 740, 646, 484,
       729, 504, 243, 566, 562, 686, 189, 699, 475, 681, 510,  58, 474,
       560, 252,  21, 313, 459, 160, 276, 191, 385, 413, 491, 343, 308,
       661, 130, 663,  99, 372,  87, 458, 330, 214, 466, 121, 614,  20,
       700,  71, 106, 270, 435, 102]), slice(None, None, None))' is an invalid key
```

I am running it on a python 3.7 environment on Windows Subsystem for Linux.

Thanks

**Comment by FlorianWilhelm** [comment]
Hi, thanks for posting this issue. The problem is that covariates is Pandas DataFrame in the provided example and `generate_data` uses the array notation as if it were a Numpy array. To fix this one would need to differentiate between arrays and dataframes within:
```
    else:
        indices = random_state.choice(covariates.shape[0], n_samples, replace=False)
        covariates = covariates[indices, :]
```
@MaximilianFranz: Do you have time to look into it?

**Comment by MaximilianFranz** [comment]
Yes, for some reason we were not considering DataFrame inputs. I'll add a check and respective transformation if required.

**Comment by MaximilianFranz** [comment]
@Tanmay-Kulkarni101 this should be fixed on `dev` along with the installation problem for py3.6.9 mentioned in #21. 
Would you be able to verify that installation works for you on Python 3.6.X? By running `python setup.py install` in the cloned directory of `dev` or by running `python setup.py dists` and then `pip install dists/*.whl`? 

Both @FlorianWilhelm and me are currently having problems with xgboost installation due to MacOS..

**Comment by Tanmay-Kulkarni101** [comment]
@FlorianWilhelm , @MaximilianFranz  I'll have a go

**Comment by Tanmay-Kulkarni101** [comment]
The problem still seems to persist, I cloned the repository and ran ```python3 setup.py install```. I found the following statement in the install:
```
creating dist
creating 'dist/JustCause-0.3.1.post0.dev6+gf6baf67-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing JustCause-0.3.1.post0.dev6+gf6baf67-py3.6.egg
creating /home/tanmay/model-36/lib/python3.6/site-packages/JustCause-0.3.1.post0.dev6+gf6baf67-py3.6.egg
Extracting JustCause-0.3.1.post0.dev6+gf6baf67-py3.6.egg to /home/tanmay/model-36/lib/python3.6/site-packages
  File "/home/tanmay/model-36/lib/python3.6/site-packages/JustCause-0.3.1.post0.dev6+gf6baf67-py3.6.egg/justcause/data/transport.py", line 8
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined

Adding JustCause 0.3.1.post0.dev6+gf6baf67 to easy-install.pth file

Installed /home/tanmay/model-36/lib/python3.6/site-packages/JustCause-0.3.1.post0.dev6+gf6baf67-py3.6.egg
Processing dependencies for JustCause==0.3.1.post0.dev6+gf6baf67
Searching for scikit-learn
```
On running manually, it gave the expected error:
```
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import justcause
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tanmay/model-36/lib/python3.6/site-packages/JustCause-0.3.1.post0.dev6+gf6baf67-py3.6.egg/justcause/__init__.py", line 4, in <module>
    from . import data
  File "/home/tanmay/model-36/lib/python3.6/site-packages/JustCause-0.3.1.post0.dev6+gf6baf67-py3.6.egg/justcause/data/__init__.py", line 14, in <module>
    from . import sets
  File "/home/tanmay/model-36/lib/python3.6/site-packages/JustCause-0.3.1.post0.dev6+gf6baf67-py3.6.egg/justcause/data/sets/__init__.py", line 24, in <module>
    from .ibm import load_ibm
  File "/home/tanmay/model-36/lib/python3.6/site-packages/JustCause-0.3.1.post0.dev6+gf6baf67-py3.6.egg/justcause/data/sets/ibm.py", line 24, in <module>
    from ..transport import get_covariates_df, get_outcomes_df
  File "/home/tanmay/model-36/lib/python3.6/site-packages/JustCause-0.3.1.post0.dev6+gf6baf67-py3.6.egg/justcause/data/transport.py", line 8
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by MaximilianFranz** [comment]
Did you make sure to pull/clone the `dev` branch? 
Find it [here!](https://github.com/inovex/justcause/tree/dev)

Because [there](https://github.com/inovex/justcause/blob/dev/src/justcause/data/transport.py) the import is commented out.

**Comment by FlorianWilhelm** [comment]
Seems like everything works now. I will upload a version `0.3.2` in a minute.

**Comment by Tanmay-Kulkarni101** [comment]
Sorry, for that guys, I had cloned the master branch :sweat_smile:. I did another test once, you had merged the changes. I seems to be working fine. Keep up the good work guys!:+1:
